### ISSUE TITLE
dll going from .Net Framework 3.5 to 4.0 after stripping

### ISSUE THREAD

**Issue by Raicuparta** [BepInEx/NStrip#1]
Using the files `Assembly-CSharp.dll` and `Assembly-CSharp-firstpass.dll` from Firewatch 1.0.9 (GOG version).

`Assembly-CSharp.dll` works fine, it stays in 3.5. But `Assembly-CSharp-firstpass.dll` for some reason gets bumped to Framework 4.0 (with or without publicizing), and this seems to make it break on building a project that uses that dll as a dependency. Don't think I can update the project to 4.0 because that breaks other stuff.

**Comment by PhantomGamers** [comment]
Do you see the same behavior if you use the `--keep-resources` argument?

**Comment by Raicuparta** [comment]
Tried `--keep-resources` just now, doesn't seem to make a difference. Also tried all the different stripping methods.

**Comment by bbepis** [comment]
Would you be able to send me the original DLL files?

If you don't want to upload it to github, you can DM me through https://discord.gg/RFKW4ZBW

**Comment by bbepis** [comment]
This should be fixed in v1.3

Thanks to @Raicuparta helping me debug this, the issue was that NStrip was adding a reference to mscorlib 4.0 due to using Cecil's runtime type resolution (NStrip is a .NET 4.5.2 project, so Cecil was assuming that we wanted mscorlib 4.0)

Creating type references in respect to the mscorlib used by the target assembly fixes this.
See these two links:
https://stackoverflow.com/questions/15603220/mono-cecil-write-library-target-framework-3-5-it-writes-reference-to-mscorlib
https://stackoverflow.com/questions/33532502/mono-cecil-wrong-mscorlib-version

Please reopen this issue if you're experiencing this issue again
